name: Build, Push Docker & Deploy Terraform

on:
  workflow_dispatch:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/ci-all.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    env:
      AWS_REGION: ap-south-1
      ECR_REPO: hello-lambda

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create ECR repository if not exists
        env:
          AWS_REGION: ap-south-1
          ECR_REPO: hello-lambda
        run: |
          ACCOUNT_ID=012889719104
          aws ecr describe-repositories --repository-names "$ECR_REPO" --region $AWS_REGION || \
          aws ecr create-repository --repository-name "$ECR_REPO" --region $AWS_REGION
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set variables for ECR
        id: prep
        run: |
          ACCOUNT_ID=012889719104
          ECR_URI="$ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/hello-lambda"
          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          echo "IMAGE_URI=$ECR_URI:latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $ECR_URI:latest ./app
      
      - name: Push image to Amazon ECR
        run: |
          docker push $ECR_URI:latest
      
      - name: Update terraform.tfvars with new image_uri
        run: |
          sed -i "s|^image_uri *=.*|image_uri = \"$ECR_URI:latest\"|g" terraform.tfvars

      - name: Delete all other tags except latest (optional)
        run: |
          ACCOUNT_ID=012889719104
          REPO=hello-lambda
          for digest in $(aws ecr list-images --repository-name $REPO --region ap-south-1 --query 'imageIds[?imageTag!=`latest`].imageDigest' --output text); do
            aws ecr batch-delete-image --repository-name $REPO --region ap-south-1 --image-ids imageDigest=$digest
          done

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
