name: Terraform Destroy All

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Destroy environment resources (e.g., Lambda, IAM, etc.)
      - name: Terraform Init (Environment)
        run: terraform -chdir=terraform/environments/dev init

      - name: Terraform Destroy (Environment)
        run: terraform -chdir=terraform/environments/dev destroy -auto-approve

      # Destroy bootstrap resources (S3, DynamoDB, ECR)
      - name: Terraform Init (Bootstrap)
        run: terraform -chdir=terraform/bootstrap init

      - name: Terraform Destroy (Bootstrap)
        run: terraform -chdir=terraform/bootstrap destroy -auto-approve
